### ISSUE TITLE
python 范例的 stereo

### ISSUE THREAD

**Issue by javierztl** [DIYer22/stereo_matching_crestereo#1]
请问python 范例里面的 stereo.set_stereo_matching(matching),  stereo是在哪里定义或者是import呀，我在https://github.com/DIYer22/calibrating 看到 stereo = calibrating.Stereo(caml, camr)， 但是关于caml, camr 要如何定义.
谢谢

**Comment by DIYer22** [comment]
用 calibrating 标定左右相机就可以了:
https://github.com/DIYer22/calibrating/blob/master/example/checkboard_example_cn.py#L26

推荐你过一遍 https://github.com/DIYer22/calibrating/blob/master/calibrating/stereo_camera.py#L543

通过修改样例中的 stereo yaml 来设置相机内外参,然后直接 load stereo

stereo = Stereo.load(yaml_path)
